name: Java CI (Maven)

on:
  push:
    branches: [ "main", "develop", "feature/**", "hotfix/**" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn -B -ntp clean verify

      - name: Upload WAR file
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: bookstore-war
          path: "**/target/*.war"
          if-no-files-found: ignore
